### ISSUE TITLE
CodeChef Solve count is not working properly

### ISSUE THREAD

**Issue by Sarwar05** [bacsbd/cpps#121]
I solved a few problems in Codechef, but here it shows 0. 
And I didn't add poj id, but it counts 10.

**Comment by forthright48** [comment]
@Sarwar05 What's your user id on the following sites: cpps.bacsbd.org, codechef and poj?

You didn't add POJ but it shows 10? Did you add vjudge? Maybe you solved some problems on vjudge which are from POJ. CPPS grabs solves from vjudge and adds to appropriate OJs.

**Comment by Sarwar05** [comment]
@forthright48 
cpps.bacsbd.org: Sarwar_05
codechef: sarwar05
poj: Sarwar05

**Comment by Sarwar05** [comment]
@forthright48 
in hdu i solved 1 problem but it counts 2.
handle: Zlatan05

**Comment by RaffiRaffiRaffi** [comment]
Facing the same problem.
Couple of my friends too.

**Comment by forthright48** [comment]
@Sarwar05 : About your poj solve count. You have 0 solve on POJ site, but, on vjudge you solved 10 problems that come from POJ. That's why your solve is 10 on cpps. Check your vjudge profile here: https://vjudge.net/user/SarwarIT#

**Comment by RaffiRaffiRaffi** [comment]
Thank you ^_^

**Comment by forthright48** [comment]
@Sarwar05  and @RaffiRaffiRaffi : Ok. It has been fixed on this commit: 7778fb5e585ffbc976287df0d9e7164d55508674
